$(document).ready(function(){
	$("#x1").click(function(){
		 window.location.href="../html/xunke5.html";
	})
	$("#x2").click(function(){
		 window.location.href="../html/xunke10.html";
	})
	$("#x3").click(function(){
		 window.location.href="../html/xunke.html";
	})
	$("#x4").click(function(){
		 window.location.href="../html/xunke7.html";
	})
	$("#x5").click(function(){
		 window.location.href="../html/xunke2.html";
	})
	$(".home").click(function(){
		window.location.href="../html/xunke9.html";
	})
	$(".headline").click(function(){
		$(this).find(".title3").css("display","block");
		$(this).siblings().find(".title3").css("display","none");
	})
	$(".touxiang ul li").eq(1).click(function(){
		window.location.href="../html/xunke6.html";
	})
})